import "./globals.css";
import type { Metadata } from "next";

import Header from "@/components/Header";
import {
  ChakraCacheProvider,
  NextAuthProvider,
  AppProvider,
  TanstackQueryClientProvider
} from "../providers";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <NextAuthProvider>
            <ChakraCacheProvider>
              <TanstackQueryClientProvider>
                <Suspense fallback={<Loading />}>
                  <Header />
                  <main>{children}</main>
                </Suspense>
              </TanstackQueryClientProvider>
            </ChakraCacheProvider>
          </NextAuthProvider>
        </AppProvider>
      </body>
    </html>
  );
}
