import "./globals.css";
import type { Metadata } from "next";

import Header from "@/components/Header";
import { AppProvider } from "@/store";
import NextAuthProvider from "../components/Provider";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <NextAuthProvider>
            <Header />
            <main>{children}</main>
          </NextAuthProvider>
        </AppProvider>
      </body>
    </html>
  );
}
